# Generated by Django 3.2.3 on 2021-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210704_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertherapysession',
            name='therapy_list',
        ),
        migrations.AddField(
            model_name='usertherapysession',
            name='therapy_list',
            field=models.ManyToManyField(to='main.UserTherapyActivity'),
        ),
    ]
