# Generated by Django 3.2.3 on 2021-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_therapyactivity_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyactivity',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
