# Generated by Django 3.2.3 on 2021-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_therapyactivity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyactivity',
            name='name',
            field=models.CharField(default=None, max_length=300, verbose_name='Activity_Name'),
        ),
    ]
