# Generated by Django 3.2.3 on 2021-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_therapyactivity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertherapysession',
            name='therapy_list',
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='UserTherapyActivity',
        ),
        migrations.DeleteModel(
            name='UserTherapySession',
        ),
    ]
